version: "3.3"
services:
  net_core:
    image: cocoafaith/netcore2-gdiplus:2.0
    container_name: ink_yjd
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./app:/app
    command: YJD.ZRX.Web.dll
